{% set name = "polygon-api-client" %}
{% set version = "1.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f836c56bb0b71185ed9a490884519064908a9a07987692dfc39d4774306f48c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - certifi >=2022.5.18,<2024
    - setuptools
    - urllib3 >=1.26.9,<2
    - websockets >=10.3,<13

test:
  imports:
    - polygon
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/polygon-io/client-python
  summary: Polygon API client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - yehoshuadimarsky
