{% set name = "polygon-api-client" %}
{% set version = "1.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 749bec8cce5c9e9bf571e7d2a86921d3e3319e6583b034d6edfe62e1f6d07861

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - python >=3.8
    - certifi >=2022.5.18,<2024
    - setuptools
    - urllib3 >=1.26.9,<2
    - websockets >=10.3,<12

test:
  imports:
    - polygon

about:
  home: https://github.com/polygon-io/client-python
  summary: Polygon API client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - yehoshuadimarsky
