{% set name = "polygon-api-client" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polygon-api-client-{{ version }}.tar.gz
  sha256: fb8f817b7f246ed960e74aebde6f725ac845f39f2c390a4ca9df93dad3a7273d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.22.0
    - websocket-client >=0.56.0
    - websockets >=8.0.2

test:
  imports:
    - polygon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/polygon-io/client-python
  summary: Polygon API client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yehoshuadimarsky
